// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] wb_rv_adr_i,
    input  [31:0] wb_rv_dat_i,
    input   [3:0] wb_rv_sel_i,
    input         wb_rv_we_i,
    input         wb_rv_cyc_i,
    input         wb_rv_stb_i,
    input   [2:0] wb_rv_cti_i,
    input   [1:0] wb_rv_bte_i,
    output [31:0] wb_rv_dat_o,
    output        wb_rv_ack_o,
    output        wb_rv_err_o,
    output        wb_rv_rty_o,
    input  [31:0] wb_daq_master_adr_i,
    input  [31:0] wb_daq_master_dat_i,
    input   [3:0] wb_daq_master_sel_i,
    input         wb_daq_master_we_i,
    input         wb_daq_master_cyc_i,
    input         wb_daq_master_stb_i,
    input   [2:0] wb_daq_master_cti_i,
    input   [1:0] wb_daq_master_bte_i,
    output [31:0] wb_daq_master_dat_o,
    output        wb_daq_master_ack_o,
    output        wb_daq_master_err_o,
    output        wb_daq_master_rty_o,
    input  [31:0] wb_dsp_master_adr_i,
    input  [31:0] wb_dsp_master_dat_i,
    input   [3:0] wb_dsp_master_sel_i,
    input         wb_dsp_master_we_i,
    input         wb_dsp_master_cyc_i,
    input         wb_dsp_master_stb_i,
    input   [2:0] wb_dsp_master_cti_i,
    input   [1:0] wb_dsp_master_bte_i,
    output [31:0] wb_dsp_master_dat_o,
    output        wb_dsp_master_ack_o,
    output        wb_dsp_master_err_o,
    output        wb_dsp_master_rty_o,
    output [31:0] wb_uart_adr_o,
    output [31:0] wb_uart_dat_o,
    output  [3:0] wb_uart_sel_o,
    output        wb_uart_we_o,
    output        wb_uart_cyc_o,
    output        wb_uart_stb_o,
    output  [2:0] wb_uart_cti_o,
    output  [1:0] wb_uart_bte_o,
    input  [31:0] wb_uart_dat_i,
    input         wb_uart_ack_i,
    input         wb_uart_err_i,
    input         wb_uart_rty_i,
    output [31:0] wb_dsp_slave_adr_o,
    output [31:0] wb_dsp_slave_dat_o,
    output  [3:0] wb_dsp_slave_sel_o,
    output        wb_dsp_slave_we_o,
    output        wb_dsp_slave_cyc_o,
    output        wb_dsp_slave_stb_o,
    output  [2:0] wb_dsp_slave_cti_o,
    output  [1:0] wb_dsp_slave_bte_o,
    input  [31:0] wb_dsp_slave_dat_i,
    input         wb_dsp_slave_ack_i,
    input         wb_dsp_slave_err_i,
    input         wb_dsp_slave_rty_i,
    output [31:0] wb_daq_slave_adr_o,
    output [31:0] wb_daq_slave_dat_o,
    output  [3:0] wb_daq_slave_sel_o,
    output        wb_daq_slave_we_o,
    output        wb_daq_slave_cyc_o,
    output        wb_daq_slave_stb_o,
    output  [2:0] wb_daq_slave_cti_o,
    output  [1:0] wb_daq_slave_bte_o,
    input  [31:0] wb_daq_slave_dat_i,
    input         wb_daq_slave_ack_i,
    input         wb_daq_slave_err_i,
    input         wb_daq_slave_rty_i,
    output [31:0] wb_timer_adr_o,
    output [31:0] wb_timer_dat_o,
    output  [3:0] wb_timer_sel_o,
    output        wb_timer_we_o,
    output        wb_timer_cyc_o,
    output        wb_timer_stb_o,
    output  [2:0] wb_timer_cti_o,
    output  [1:0] wb_timer_bte_o,
    input  [31:0] wb_timer_dat_i,
    input         wb_timer_ack_i,
    input         wb_timer_err_i,
    input         wb_timer_rty_i,
    output [31:0] wb_gpio_adr_o,
    output [31:0] wb_gpio_dat_o,
    output  [3:0] wb_gpio_sel_o,
    output        wb_gpio_we_o,
    output        wb_gpio_cyc_o,
    output        wb_gpio_stb_o,
    output  [2:0] wb_gpio_cti_o,
    output  [1:0] wb_gpio_bte_o,
    input  [31:0] wb_gpio_dat_i,
    input         wb_gpio_ack_i,
    input         wb_gpio_err_i,
    input         wb_gpio_rty_i,
    output [31:0] wb_ram_adr_o,
    output [31:0] wb_ram_dat_o,
    output  [3:0] wb_ram_sel_o,
    output        wb_ram_we_o,
    output        wb_ram_cyc_o,
    output        wb_ram_stb_o,
    output  [2:0] wb_ram_cti_o,
    output  [1:0] wb_ram_bte_o,
    input  [31:0] wb_ram_dat_i,
    input         wb_ram_ack_i,
    input         wb_ram_err_i,
    input         wb_ram_rty_i,
    output [31:0] wb_rom_adr_o,
    output [31:0] wb_rom_dat_o,
    output  [3:0] wb_rom_sel_o,
    output        wb_rom_we_o,
    output        wb_rom_cyc_o,
    output        wb_rom_stb_o,
    output  [2:0] wb_rom_cti_o,
    output  [1:0] wb_rom_bte_o,
    input  [31:0] wb_rom_dat_i,
    input         wb_rom_ack_i,
    input         wb_rom_err_i,
    input         wb_rom_rty_i,
    output [31:0] wb_fw_interface_adr_o,
    output [31:0] wb_fw_interface_dat_o,
    output  [3:0] wb_fw_interface_sel_o,
    output        wb_fw_interface_we_o,
    output        wb_fw_interface_cyc_o,
    output        wb_fw_interface_stb_o,
    output  [2:0] wb_fw_interface_cti_o,
    output  [1:0] wb_fw_interface_bte_o,
    input  [31:0] wb_fw_interface_dat_i,
    input         wb_fw_interface_ack_i,
    input         wb_fw_interface_err_i,
    input         wb_fw_interface_rty_i);

wire [31:0] wb_m2s_rv_ram_adr;
wire [31:0] wb_m2s_rv_ram_dat;
wire  [3:0] wb_m2s_rv_ram_sel;
wire        wb_m2s_rv_ram_we;
wire        wb_m2s_rv_ram_cyc;
wire        wb_m2s_rv_ram_stb;
wire  [2:0] wb_m2s_rv_ram_cti;
wire  [1:0] wb_m2s_rv_ram_bte;
wire [31:0] wb_s2m_rv_ram_dat;
wire        wb_s2m_rv_ram_ack;
wire        wb_s2m_rv_ram_err;
wire        wb_s2m_rv_ram_rty;
wire [31:0] wb_m2s_rv_rom_adr;
wire [31:0] wb_m2s_rv_rom_dat;
wire  [3:0] wb_m2s_rv_rom_sel;
wire        wb_m2s_rv_rom_we;
wire        wb_m2s_rv_rom_cyc;
wire        wb_m2s_rv_rom_stb;
wire  [2:0] wb_m2s_rv_rom_cti;
wire  [1:0] wb_m2s_rv_rom_bte;
wire [31:0] wb_s2m_rv_rom_dat;
wire        wb_s2m_rv_rom_ack;
wire        wb_s2m_rv_rom_err;
wire        wb_s2m_rv_rom_rty;
wire [31:0] wb_m2s_daq_master_ram_adr;
wire [31:0] wb_m2s_daq_master_ram_dat;
wire  [3:0] wb_m2s_daq_master_ram_sel;
wire        wb_m2s_daq_master_ram_we;
wire        wb_m2s_daq_master_ram_cyc;
wire        wb_m2s_daq_master_ram_stb;
wire  [2:0] wb_m2s_daq_master_ram_cti;
wire  [1:0] wb_m2s_daq_master_ram_bte;
wire [31:0] wb_s2m_daq_master_ram_dat;
wire        wb_s2m_daq_master_ram_ack;
wire        wb_s2m_daq_master_ram_err;
wire        wb_s2m_daq_master_ram_rty;
wire [31:0] wb_m2s_daq_master_rom_adr;
wire [31:0] wb_m2s_daq_master_rom_dat;
wire  [3:0] wb_m2s_daq_master_rom_sel;
wire        wb_m2s_daq_master_rom_we;
wire        wb_m2s_daq_master_rom_cyc;
wire        wb_m2s_daq_master_rom_stb;
wire  [2:0] wb_m2s_daq_master_rom_cti;
wire  [1:0] wb_m2s_daq_master_rom_bte;
wire [31:0] wb_s2m_daq_master_rom_dat;
wire        wb_s2m_daq_master_rom_ack;
wire        wb_s2m_daq_master_rom_err;
wire        wb_s2m_daq_master_rom_rty;
wire [31:0] wb_m2s_dsp_master_ram_adr;
wire [31:0] wb_m2s_dsp_master_ram_dat;
wire  [3:0] wb_m2s_dsp_master_ram_sel;
wire        wb_m2s_dsp_master_ram_we;
wire        wb_m2s_dsp_master_ram_cyc;
wire        wb_m2s_dsp_master_ram_stb;
wire  [2:0] wb_m2s_dsp_master_ram_cti;
wire  [1:0] wb_m2s_dsp_master_ram_bte;
wire [31:0] wb_s2m_dsp_master_ram_dat;
wire        wb_s2m_dsp_master_ram_ack;
wire        wb_s2m_dsp_master_ram_err;
wire        wb_s2m_dsp_master_ram_rty;
wire [31:0] wb_m2s_dsp_master_rom_adr;
wire [31:0] wb_m2s_dsp_master_rom_dat;
wire  [3:0] wb_m2s_dsp_master_rom_sel;
wire        wb_m2s_dsp_master_rom_we;
wire        wb_m2s_dsp_master_rom_cyc;
wire        wb_m2s_dsp_master_rom_stb;
wire  [2:0] wb_m2s_dsp_master_rom_cti;
wire  [1:0] wb_m2s_dsp_master_rom_bte;
wire [31:0] wb_s2m_dsp_master_rom_dat;
wire        wb_s2m_dsp_master_rom_ack;
wire        wb_s2m_dsp_master_rom_err;
wire        wb_s2m_dsp_master_rom_rty;

wb_mux
  #(.num_slaves (8),
    .MATCH_ADDR ({32'h20000000, 32'h00000000, 32'h40000000, 32'he0000000, 32'h40100000, 32'h40200000, 32'h40300000, 32'h40400000}),
    .MATCH_MASK ({32'hffff8000, 32'hffff8000, 32'hffffffe0, 32'hffffff80, 32'hffff8000, 32'hffff8000, 32'hffff8000, 32'hffff8000}))
 wb_mux_rv
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_rv_adr_i),
    .wbm_dat_i (wb_rv_dat_i),
    .wbm_sel_i (wb_rv_sel_i),
    .wbm_we_i  (wb_rv_we_i),
    .wbm_cyc_i (wb_rv_cyc_i),
    .wbm_stb_i (wb_rv_stb_i),
    .wbm_cti_i (wb_rv_cti_i),
    .wbm_bte_i (wb_rv_bte_i),
    .wbm_dat_o (wb_rv_dat_o),
    .wbm_ack_o (wb_rv_ack_o),
    .wbm_err_o (wb_rv_err_o),
    .wbm_rty_o (wb_rv_rty_o),
    .wbs_adr_o ({wb_m2s_rv_ram_adr, wb_m2s_rv_rom_adr, wb_uart_adr_o, wb_fw_interface_adr_o, wb_dsp_slave_adr_o, wb_daq_slave_adr_o, wb_timer_adr_o, wb_gpio_adr_o}),
    .wbs_dat_o ({wb_m2s_rv_ram_dat, wb_m2s_rv_rom_dat, wb_uart_dat_o, wb_fw_interface_dat_o, wb_dsp_slave_dat_o, wb_daq_slave_dat_o, wb_timer_dat_o, wb_gpio_dat_o}),
    .wbs_sel_o ({wb_m2s_rv_ram_sel, wb_m2s_rv_rom_sel, wb_uart_sel_o, wb_fw_interface_sel_o, wb_dsp_slave_sel_o, wb_daq_slave_sel_o, wb_timer_sel_o, wb_gpio_sel_o}),
    .wbs_we_o  ({wb_m2s_rv_ram_we, wb_m2s_rv_rom_we, wb_uart_we_o, wb_fw_interface_we_o, wb_dsp_slave_we_o, wb_daq_slave_we_o, wb_timer_we_o, wb_gpio_we_o}),
    .wbs_cyc_o ({wb_m2s_rv_ram_cyc, wb_m2s_rv_rom_cyc, wb_uart_cyc_o, wb_fw_interface_cyc_o, wb_dsp_slave_cyc_o, wb_daq_slave_cyc_o, wb_timer_cyc_o, wb_gpio_cyc_o}),
    .wbs_stb_o ({wb_m2s_rv_ram_stb, wb_m2s_rv_rom_stb, wb_uart_stb_o, wb_fw_interface_stb_o, wb_dsp_slave_stb_o, wb_daq_slave_stb_o, wb_timer_stb_o, wb_gpio_stb_o}),
    .wbs_cti_o ({wb_m2s_rv_ram_cti, wb_m2s_rv_rom_cti, wb_uart_cti_o, wb_fw_interface_cti_o, wb_dsp_slave_cti_o, wb_daq_slave_cti_o, wb_timer_cti_o, wb_gpio_cti_o}),
    .wbs_bte_o ({wb_m2s_rv_ram_bte, wb_m2s_rv_rom_bte, wb_uart_bte_o, wb_fw_interface_bte_o, wb_dsp_slave_bte_o, wb_daq_slave_bte_o, wb_timer_bte_o, wb_gpio_bte_o}),
    .wbs_dat_i ({wb_s2m_rv_ram_dat, wb_s2m_rv_rom_dat, wb_uart_dat_i, wb_fw_interface_dat_i, wb_dsp_slave_dat_i, wb_daq_slave_dat_i, wb_timer_dat_i, wb_gpio_dat_i}),
    .wbs_ack_i ({wb_s2m_rv_ram_ack, wb_s2m_rv_rom_ack, wb_uart_ack_i, wb_fw_interface_ack_i, wb_dsp_slave_ack_i, wb_daq_slave_ack_i, wb_timer_ack_i, wb_gpio_ack_i}),
    .wbs_err_i ({wb_s2m_rv_ram_err, wb_s2m_rv_rom_err, wb_uart_err_i, wb_fw_interface_err_i, wb_dsp_slave_err_i, wb_daq_slave_err_i, wb_timer_err_i, wb_gpio_err_i}),
    .wbs_rty_i ({wb_s2m_rv_ram_rty, wb_s2m_rv_rom_rty, wb_uart_rty_i, wb_fw_interface_rty_i, wb_dsp_slave_rty_i, wb_daq_slave_rty_i, wb_timer_rty_i, wb_gpio_rty_i}));

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h20000000, 32'h00000000}),
    .MATCH_MASK ({32'hffff8000, 32'hffff8000}))
 wb_mux_daq_master
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_daq_master_adr_i),
    .wbm_dat_i (wb_daq_master_dat_i),
    .wbm_sel_i (wb_daq_master_sel_i),
    .wbm_we_i  (wb_daq_master_we_i),
    .wbm_cyc_i (wb_daq_master_cyc_i),
    .wbm_stb_i (wb_daq_master_stb_i),
    .wbm_cti_i (wb_daq_master_cti_i),
    .wbm_bte_i (wb_daq_master_bte_i),
    .wbm_dat_o (wb_daq_master_dat_o),
    .wbm_ack_o (wb_daq_master_ack_o),
    .wbm_err_o (wb_daq_master_err_o),
    .wbm_rty_o (wb_daq_master_rty_o),
    .wbs_adr_o ({wb_m2s_daq_master_ram_adr, wb_m2s_daq_master_rom_adr}),
    .wbs_dat_o ({wb_m2s_daq_master_ram_dat, wb_m2s_daq_master_rom_dat}),
    .wbs_sel_o ({wb_m2s_daq_master_ram_sel, wb_m2s_daq_master_rom_sel}),
    .wbs_we_o  ({wb_m2s_daq_master_ram_we, wb_m2s_daq_master_rom_we}),
    .wbs_cyc_o ({wb_m2s_daq_master_ram_cyc, wb_m2s_daq_master_rom_cyc}),
    .wbs_stb_o ({wb_m2s_daq_master_ram_stb, wb_m2s_daq_master_rom_stb}),
    .wbs_cti_o ({wb_m2s_daq_master_ram_cti, wb_m2s_daq_master_rom_cti}),
    .wbs_bte_o ({wb_m2s_daq_master_ram_bte, wb_m2s_daq_master_rom_bte}),
    .wbs_dat_i ({wb_s2m_daq_master_ram_dat, wb_s2m_daq_master_rom_dat}),
    .wbs_ack_i ({wb_s2m_daq_master_ram_ack, wb_s2m_daq_master_rom_ack}),
    .wbs_err_i ({wb_s2m_daq_master_ram_err, wb_s2m_daq_master_rom_err}),
    .wbs_rty_i ({wb_s2m_daq_master_ram_rty, wb_s2m_daq_master_rom_rty}));

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h20000000, 32'h00000000}),
    .MATCH_MASK ({32'hffff8000, 32'hffff8000}))
 wb_mux_dsp_master
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_dsp_master_adr_i),
    .wbm_dat_i (wb_dsp_master_dat_i),
    .wbm_sel_i (wb_dsp_master_sel_i),
    .wbm_we_i  (wb_dsp_master_we_i),
    .wbm_cyc_i (wb_dsp_master_cyc_i),
    .wbm_stb_i (wb_dsp_master_stb_i),
    .wbm_cti_i (wb_dsp_master_cti_i),
    .wbm_bte_i (wb_dsp_master_bte_i),
    .wbm_dat_o (wb_dsp_master_dat_o),
    .wbm_ack_o (wb_dsp_master_ack_o),
    .wbm_err_o (wb_dsp_master_err_o),
    .wbm_rty_o (wb_dsp_master_rty_o),
    .wbs_adr_o ({wb_m2s_dsp_master_ram_adr, wb_m2s_dsp_master_rom_adr}),
    .wbs_dat_o ({wb_m2s_dsp_master_ram_dat, wb_m2s_dsp_master_rom_dat}),
    .wbs_sel_o ({wb_m2s_dsp_master_ram_sel, wb_m2s_dsp_master_rom_sel}),
    .wbs_we_o  ({wb_m2s_dsp_master_ram_we, wb_m2s_dsp_master_rom_we}),
    .wbs_cyc_o ({wb_m2s_dsp_master_ram_cyc, wb_m2s_dsp_master_rom_cyc}),
    .wbs_stb_o ({wb_m2s_dsp_master_ram_stb, wb_m2s_dsp_master_rom_stb}),
    .wbs_cti_o ({wb_m2s_dsp_master_ram_cti, wb_m2s_dsp_master_rom_cti}),
    .wbs_bte_o ({wb_m2s_dsp_master_ram_bte, wb_m2s_dsp_master_rom_bte}),
    .wbs_dat_i ({wb_s2m_dsp_master_ram_dat, wb_s2m_dsp_master_rom_dat}),
    .wbs_ack_i ({wb_s2m_dsp_master_ram_ack, wb_s2m_dsp_master_rom_ack}),
    .wbs_err_i ({wb_s2m_dsp_master_ram_err, wb_s2m_dsp_master_rom_err}),
    .wbs_rty_i ({wb_s2m_dsp_master_ram_rty, wb_s2m_dsp_master_rom_rty}));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_ram
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_rv_ram_adr, wb_m2s_daq_master_ram_adr, wb_m2s_dsp_master_ram_adr}),
    .wbm_dat_i ({wb_m2s_rv_ram_dat, wb_m2s_daq_master_ram_dat, wb_m2s_dsp_master_ram_dat}),
    .wbm_sel_i ({wb_m2s_rv_ram_sel, wb_m2s_daq_master_ram_sel, wb_m2s_dsp_master_ram_sel}),
    .wbm_we_i  ({wb_m2s_rv_ram_we, wb_m2s_daq_master_ram_we, wb_m2s_dsp_master_ram_we}),
    .wbm_cyc_i ({wb_m2s_rv_ram_cyc, wb_m2s_daq_master_ram_cyc, wb_m2s_dsp_master_ram_cyc}),
    .wbm_stb_i ({wb_m2s_rv_ram_stb, wb_m2s_daq_master_ram_stb, wb_m2s_dsp_master_ram_stb}),
    .wbm_cti_i ({wb_m2s_rv_ram_cti, wb_m2s_daq_master_ram_cti, wb_m2s_dsp_master_ram_cti}),
    .wbm_bte_i ({wb_m2s_rv_ram_bte, wb_m2s_daq_master_ram_bte, wb_m2s_dsp_master_ram_bte}),
    .wbm_dat_o ({wb_s2m_rv_ram_dat, wb_s2m_daq_master_ram_dat, wb_s2m_dsp_master_ram_dat}),
    .wbm_ack_o ({wb_s2m_rv_ram_ack, wb_s2m_daq_master_ram_ack, wb_s2m_dsp_master_ram_ack}),
    .wbm_err_o ({wb_s2m_rv_ram_err, wb_s2m_daq_master_ram_err, wb_s2m_dsp_master_ram_err}),
    .wbm_rty_o ({wb_s2m_rv_ram_rty, wb_s2m_daq_master_ram_rty, wb_s2m_dsp_master_ram_rty}),
    .wbs_adr_o (wb_ram_adr_o),
    .wbs_dat_o (wb_ram_dat_o),
    .wbs_sel_o (wb_ram_sel_o),
    .wbs_we_o  (wb_ram_we_o),
    .wbs_cyc_o (wb_ram_cyc_o),
    .wbs_stb_o (wb_ram_stb_o),
    .wbs_cti_o (wb_ram_cti_o),
    .wbs_bte_o (wb_ram_bte_o),
    .wbs_dat_i (wb_ram_dat_i),
    .wbs_ack_i (wb_ram_ack_i),
    .wbs_err_i (wb_ram_err_i),
    .wbs_rty_i (wb_ram_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_rom
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_rv_rom_adr, wb_m2s_daq_master_rom_adr, wb_m2s_dsp_master_rom_adr}),
    .wbm_dat_i ({wb_m2s_rv_rom_dat, wb_m2s_daq_master_rom_dat, wb_m2s_dsp_master_rom_dat}),
    .wbm_sel_i ({wb_m2s_rv_rom_sel, wb_m2s_daq_master_rom_sel, wb_m2s_dsp_master_rom_sel}),
    .wbm_we_i  ({wb_m2s_rv_rom_we, wb_m2s_daq_master_rom_we, wb_m2s_dsp_master_rom_we}),
    .wbm_cyc_i ({wb_m2s_rv_rom_cyc, wb_m2s_daq_master_rom_cyc, wb_m2s_dsp_master_rom_cyc}),
    .wbm_stb_i ({wb_m2s_rv_rom_stb, wb_m2s_daq_master_rom_stb, wb_m2s_dsp_master_rom_stb}),
    .wbm_cti_i ({wb_m2s_rv_rom_cti, wb_m2s_daq_master_rom_cti, wb_m2s_dsp_master_rom_cti}),
    .wbm_bte_i ({wb_m2s_rv_rom_bte, wb_m2s_daq_master_rom_bte, wb_m2s_dsp_master_rom_bte}),
    .wbm_dat_o ({wb_s2m_rv_rom_dat, wb_s2m_daq_master_rom_dat, wb_s2m_dsp_master_rom_dat}),
    .wbm_ack_o ({wb_s2m_rv_rom_ack, wb_s2m_daq_master_rom_ack, wb_s2m_dsp_master_rom_ack}),
    .wbm_err_o ({wb_s2m_rv_rom_err, wb_s2m_daq_master_rom_err, wb_s2m_dsp_master_rom_err}),
    .wbm_rty_o ({wb_s2m_rv_rom_rty, wb_s2m_daq_master_rom_rty, wb_s2m_dsp_master_rom_rty}),
    .wbs_adr_o (wb_rom_adr_o),
    .wbs_dat_o (wb_rom_dat_o),
    .wbs_sel_o (wb_rom_sel_o),
    .wbs_we_o  (wb_rom_we_o),
    .wbs_cyc_o (wb_rom_cyc_o),
    .wbs_stb_o (wb_rom_stb_o),
    .wbs_cti_o (wb_rom_cti_o),
    .wbs_bte_o (wb_rom_bte_o),
    .wbs_dat_i (wb_rom_dat_i),
    .wbs_ack_i (wb_rom_ack_i),
    .wbs_err_i (wb_rom_err_i),
    .wbs_rty_i (wb_rom_rty_i));

endmodule
